### ISSUE TITLE
Support inline body

### ISSUE THREAD

**Issue by jonashaag** [peter-evans/create-issue-from-file#1193]
For very short bodies it would be convenient to be able to specify them inline:

```yml
with:
  title: Blah blah
  content: |
    Blah blah

    Blah blah ${{ matrix.SOME_VARIABLE }}
```
