### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by isaak654** [peter-evans/create-issue-from-file#1220]
<img alt="Error: Resource not accessible by integration" src="https://github.com/peter-evans/create-issue-from-file/assets/12372772/18317f3a-31a8-4e70-8650-8cc0903f024f" height="250px">

Action error: https://github.com/sandboxie-plus/sandboxie-docs/actions/runs/5878357898/job/15940266590?pr=122#step:5:12
List of permissions:
```
    permissions:
      contents: read
      issues: write
      actions: write
      pull-requests: write
```

Do you know what's missing? For reasons I don't understand, the error message is only displayed within pull requests.

If you have the answer, please update your README.md accordingly.

Thanks.
