### ISSUE TITLE
Avoid creating duplicate issues

### ISSUE THREAD

**Issue by expipiplus1** [peter-evans/create-issue-from-file#298]
It would be great to be able to avoid creating an issue when one with the same title already exists (optionally I suppose)

**Comment by peter-evans** [comment]
Hi @expipiplus1 

Good idea. I'll look into adding this feature.

**Comment by expipiplus1** [comment]
Thank you!

**Comment by expipiplus1** [comment]
At the moment I'm doing something hacky like this:

```yaml
    - id: check_issue
      if: ${{ failure() }}
      run: |
        issue_title=blah
        echo "::set-output name=issue_title::$issue_title"
        echo "::set-output name=create_issue::true"
        hub issue --state open --format $'%U %t\n' | grep -F "$issue_title" | while read u; do
          echo "Issue already exists: $u"
          echo "::set-output name=create_issue::false"
        done
      env:
        GITHUB_TOKEN: ${{ secrets.TUVOK_TOKEN }}

    - name: Create issue for failure
      if: ${{ failure() && steps.check_issue.outputs.create_issue == 'true' }}
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: ${{ steps.check_issue.outputs.issue_title }}
        content-filepath: ~/issue_body
        token: ${{ secrets.TUVOK_TOKEN }}
```

**Comment by Dimas-commits** [comment]
Thj

**Comment by Dimas-commits** [comment]
Tchrtuyuyuy

**Comment by bajlamut** [comment]
> At the moment I'm doing something hacky like this:
> 
> ```yaml
>     - id: check_issue
>       if: ${{ failure() }}
>       run: |
>         issue_title=blah
>         echo "::set-output name=issue_title::$issue_title"
>         echo "::set-output name=create_issue::true"
>         hub issue --state open --format $'%U %t\n' | grep -F "$issue_title" | while read u; do
>           echo "Issue already exists: $u"
>           echo "::set-output name=create_issue::false"
>         done
>       env:
>         GITHUB_TOKEN: ${{ secrets.TUVOK_TOKEN }}
> 
>     - name: Create issue for failure
>       if: ${{ failure() && steps.check_issue.outputs.create_issue == 'true' }}
>       uses: peter-evans/create-issue-from-file@v2
>       with:
>         title: ${{ steps.check_issue.outputs.issue_title }}
>         content-filepath: ~/issue_body
>         token: ${{ secrets.TUVOK_TOKEN }}
> ```

.

**Comment by aisensiy** [comment]
https://github.com/peter-evans/create-issue-from-file/pull/478 Add a PR to solve this.

**Comment by peter-evans** [comment]
@aisensiy Apologies for the slow response. I really appreciate the effort you've made to implement this feature. However, it's caused me to reconsider my initial intention to add the feature to this action. I think it would be much better to separate this functionality into a new action.

There is already precedent for this with two of my other actions, [create-or-update-comment](https://github.com/peter-evans/create-or-update-comment) and [find-comment](https://github.com/peter-evans/find-comment). There are some examples [here](https://github.com/peter-evans/create-or-update-comment#where-to-find-the-id-of-a-comment) showing how they are used together.

I think GitHub actions work best when they do one job and do it well. Adding lots of functionality to one action should be avoided in my opinion. I also think separating the issue search functionality into a separate "primitive" action would allow it to be used in other situations, not just for this use case.

So my proposal is that we create a new action called `find-issue` that works in a similar way to [find-comment](https://github.com/peter-evans/find-comment). The `issue-number` output of that new action is fed into this action to update it. @aisensiy Would you be interested in creating/maintaining that action?

**Comment by aisensiy** [comment]
I think this is a better solution than mine and I'd like to have a try.

**Comment by micalevisk** [comment]
I just created an action to find the last updated issue that has the given labels: https://github.com/marketplace/actions/find-last-issue

I tested it here: https://github.com/micalevisk/awesome-nestjs/issues/5 (as you can see, the issue was updated by the bot thanks to [this](https://github.com/micalevisk/awesome-nestjs/blob/99101cfd644d50c828f3c8d400ac73e6a859b36b/.github/workflows/links_checker.yml#L62-L71))

**Comment by polarathene** [comment]
> I think GitHub actions work best when they do one job and do it well. Adding lots of functionality to one action should be avoided in my opinion.

I agree with that :+1: 

Better to have simpler maintainable actions that others can create composited actions of if they want to consolidate under one action.

---

@peter-evans what do you think of the `find-last-issue` action from @micalevisk ? If it serves the purpose well enough, it would be good to mention it to users in the README for this action?

If so it would be good to document with something like this:

```yaml
on: workflow_dispatch

jobs:
  test-issue-management:
    name: 'Test - Issue Create + Update'
    runs-on: ubuntu-22.04
    permissions:
      issues: write
    steps:
      - name: 'Prep issue body'
        run: |
          echo -e "Testing _issue_  **creation**.\nSHA: ${{ github.sha }}" > /tmp/test.md

      # Permissions (issues: read)
      - name: 'Look for an existing issue'
        id: last-issue
        uses: micalevisk/last-issue-action@v1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Match the latest updated open issue that has the automated-issue label:
        with:
          state: open
          labels: automated-issue

      # Permissions (issues: write)
      - name: 'Create a new issue, or update an existing one'
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Test issue
          content-filepath: /tmp/test.md
          # If issue_number is empty (no match found), create new issue, otherwise update the matched issue
          issue-number: ${{ steps.last-issue.outputs.issue_number }}
          # Add a label unique enough to search for:
          labels: automated-issue, some-other-label-for-triage
```

It was not obvious that the two actions supported this `create` or `update` flow (_that an empty output to an input was compatible/error-free to fallback to issue creation_)
