### ISSUE TITLE
Modify the issue if it already exists

### ISSUE THREAD

**Issue by sandorex** [peter-evans/create-issue-from-file#31]
Is it possible to implement it so that it does not create unlimited issues each time it runs?

**Comment by peter-evans** [comment]
Hi @sandorex 

I think I could add an `issue-number` input that, if provided, would allow the action to update that issue instead of creating a new one. The question is, for your use case, do you know what the issue number is?

Please explain in detail what you use case is, and if possible show your workflow.

**Comment by sandorex** [comment]
I have tests running with newest version of browsers to check if any of the files i want to read has different schema version and to make an issue when it changed

My workflow:
```yaml
# omitted cause it's not important
...

jobs:
  firefox-schema-tests:
    runs-on: ubuntu-latest
    name: Firefox Schema Tests
    steps:
      - uses: actions/checkout@v2
      - name: Run the test
        run: |
          sudo docker-compose pull
          sudo docker-compose run test --skip-missing-interpreters=false -e py36 -- -v tests/firefox/test_ff_schema.py
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: firefox-schema-cache
          path: ./.tox
      - run: |
          cat << EOF > /tmp/issue.md
          It seems that Firefox schema has changed
          The run can be found [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          EOF
        if: failure()
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v2
        if: failure()
        with:
          title: Firefox schema has changed
          content-filepath: /tmp/issue.md
          labels: firefox

# omitted cause it's not important
...
```
