### ISSUE TITLE
Is it possible to add emoji in the issue title?

### ISSUE THREAD

**Issue by ahmad-hamade** [peter-evans/create-issue-from-file#313]
Is it possible to include emoji in the issue title?

**Comment by peter-evans** [comment]
Hi @ahmad-hamade 

I don't think emojis using the colon wrapped name, like `:rocket:`, work in issue and pull request titles. However, if you paste the emoji directly into the title it works. So try setting the emoji directly in your yaml.

I've not tested this, but it might work.
```
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: An example issue 🚀
          content-filepath: ./example-content/output.md
          labels: report, automated issue
```
