### ISSUE TITLE
At the moment I'm doing something hacky like this:

### ISSUE THREAD

**Issue by Dimas-commits** [peter-evans/create-issue-from-file#351]
At the moment I'm doing something hacky like this:

```yaml
    - id: check_issue
      if: ${{ failure() }}
      run: |
        issue_title=blah
        echo "::set-output name=issue_title::$issue_title"
        echo "::set-output name=create_issue::true"
        hub issue --state open --format $'%U %t\n' | grep -F "$issue_title" | while read u; do
          echo "Issue already exists: $u"
          echo "::set-output name=create_issue::false"
        done
      env:
        GITHUB_TOKEN: ${{ secrets.TUVOK_TOKEN }}

    - name: Create issue for failure
      if: ${{ failure() && steps.check_issue.outputs.create_issue == 'true' }}
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: ${{ steps.check_issue.outputs.issue_title }}
        content-filepath: ~/issue_body
        token: ${{ secrets.TUVOK_TOKEN }}
```

_Originally posted by @expipiplus1 in https://github.com/peter-evans/create-issue-from-file/issues/298#issuecomment-704667137_
