### ISSUE TITLE
Force  latest update

### ISSUE THREAD

**Issue by tianheg** [peter-evans/create-issue-from-file#588]
when update content, old content still there

code [`.github/workflows/links_checker.yml`](https://github.com/tianheg/coding-interview-university/blob/e011b7033d1a1f898086999f86e1d09ad052efe3/.github/workflows/links_checker.yml):

```yml
name: Links Checker

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

permissions: write-all

jobs:
  link_checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check File length > 60000
        run: |
          pwd
          ls -al
          sudo chown runner:docker -R ./lychee
          ls -al
          cat ./lychee/out.md | cut -c 1-60000 >> ./lychee/out.md

      - name: Find the last open report issue
        id: last_issue
        uses: micalevisk/last-issue-action@v1.2.2
        with:
          state: open
          labels: |
            report
            automated issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: echo ${{ steps.last_issue.outputs.issue_number }}

      - name: Update last updated report issue
        if: ${{ steps.last_issue.outputs.has_found == 'true' }}
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          issue-number: ${{ steps.last_issue.outputs.issue_number }}
          labels: report, automated issue
```

**Comment by peter-evans** [comment]
Hi @tianheg 

Can you show me an Actions run (the link) where it didn't work as expected. I think the problem is most likely going to be your workflow, not the action itself.

**Comment by tianheg** [comment]
Sorry to have taken up your time, instead of do more research

The reason for this duplication is because I gave the order:

```yml
- name: Check File length > 60000
  run: |
    cat ./lychee/out.md | cut -c 1-60000 >> ./lychee/out.md
```

Now it's normal: https://github.com/tianheg/coding-interview-university/issues/1
